version: "3.3"

services:
  storybook:
    image: "${IMAGE_NAME}:${VERSION}"
    container_name: "${VERSION}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${VERSION}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${VERSION}.entrypoints=websecure"
      - "traefik.http.routers.${VERSION}.tls.certresolver=le"
      - "traefik.http.services.${VERSION}.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
