name: CI

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.16.0
    - name: Use Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm tsc --noEmit || true
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.16.0
    - name: Use Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run lint
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '14', '16' ]
    steps:
    - uses: actions/checkout@v3.0.0
      with:
        fetch-depth: "0"
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.16.0
    - name: Use Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ matrix.node }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run test:unit:coverage
    - uses: codecov/codecov-action@v2.1.0
  build:
    strategy:
      matrix:
        node: [ '14', '16' ]
    runs-on: ubuntu-20.04
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.16.0
    - name: Use Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ matrix.node }}
    - run: pnpm install
    - run: pnpm run build
  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref == 'refs/heads/main'
    env:
      GIT_COMMITTER_NAME: Scaleway Bot
      GIT_COMMITTER_EMAIL: github@scaleway.com
    steps:
    - uses: actions/checkout@v3.0.0
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.16.0
    - name: Use Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run semantic-release
      env:
        HUSKY: 0
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
