name: Teardown Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  teardown:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: rg.fr-par.scw.cloud/console-scw/scaleway-form
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Export custom variables
        run: |
          SAFE_GITHUB_HEAD_REF_SLUG_URL=$(echo $GITHUB_HEAD_REF_SLUG_URL | rev | cut -c-37 | rev | sed 's/^-//g')
          ([[ $GITHUB_REF == 'refs/heads/main' ]] && echo "BRANCH_SLUG=main" || echo "BRANCH_SLUG=$SAFE_GITHUB_HEAD_REF_SLUG_URL") >> $GITHUB_ENV

      - name: Delete Serverless Container Scaleway
        uses: philibea/scaleway-containers-deploy@v1.0.8
        id: teardown
        with:
          type: 'teardown'
          scw_dns: ${{ secrets.SCW_DNS }}
          root_zone: ${{ env.BRANCH_SLUG == 'main' }}
          scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          scw_containers_namespace_id: ${{ secrets.SCW_CONTAINERS_NAMESPACE_ID }}
          scw_registry: ${{ env.IMAGE_NAME }}:${{ env.BRANCH_SLUG }}

      - name: Update deployment status
        uses: bobheadxi/deployments@v1.3.0
        with:
          step: delete-env
          token: ${{ secrets.GH_TOKEN }}
          env: ${{ env.BRANCH_SLUG }}
